# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# Dockerfile - a 'recipe' for Docker to build an image of ubuntu-based
#              environment for building the PMDK project.
#

# Pull base image
FROM ubuntu:18.04
MAINTAINER marcin.slusarz@intel.com

ENV DEBIAN_FRONTEND noninteractive

# libfabric (optional if libfabric-dev >= 1.4.2 is installed)
ENV FABRIC_DEPS "autoconf \
	automake \
	build-essential \
	libtool \
	unzip \
	wget"

ENV VALGRIND_DEPS "autoconf \
	automake \
	build-essential \
	git"

# pmdk base
ENV BASE_DEPS "build-essential \
	git \
	pkg-config"

#	libdaxctl-dev \
#	libndctl-dev \

# benchmarks (optional)
ENV BENCH_DEPS libglib2.0-dev

# examples (optional)
ENV EXAMPLES_DEPS "libfuse-dev \
	libncurses5-dev \
	libuv1-dev"

# documentation (optional)
ENV DOC_DEPS pandoc

# tests
ENV TESTS_DEPS "bc \
	gdb \
	libc6-dbg \
	libunwind-dev \
	ndctl \
	python3 \
	ssh \
	strace"

# packaging
ENV PACKAGING_DEPS "debhelper \
	devscripts \
	fakeroot"

# CodeCov
ENV CODECOV_DEPS curl

# Coverity
ENV COVERITY_DEPS ruby gcc g++ wget

# ndctl (optional if libndctl-dev and libdaxctl-dev >= 60.1, 64.1 preferred)
ENV NDCTL_DEPS "\
       automake \
       bash-completion \
       build-essential \
       git \
       libjson-c-dev \
       libkeyutils-dev \
       libkmod-dev \
       libtool \
       libudev-dev \
       pkg-config \
       systemd \
       uuid-dev"

# misc
ENV MISC_DEPS "clang \
	clang-format \
	flake8 \
	sudo \
	whois linux-tools-azure linux-tools-5.0.0-1035-azure ca-certificates"

# Copy install valgrind script
COPY install-valgrind.sh install-valgrind.sh

# Copy install libfabric script
COPY install-libfabric.sh install-libfabric.sh

# Copy install libndctl script
COPY install-libndctl.sh install-libndctl.sh

# Update the Apt cache and install basic tools
RUN apt-get update && apt-get dist-upgrade -y \
	&& apt-get install -y --no-install-recommends \
	$NDCTL_DEPS \
	$FABRIC_DEPS \
	$BASE_DEPS \
	$BENCH_DEPS \
	$EXAMPLES_DEPS \
	$DOC_DEPS \
	$TESTS_DEPS \
	$PACKAGING_DEPS \
	$CODECOV_DEPS \
	$MISC_DEPS \
	&& ./install-libfabric.sh \
	&& ./install-libndctl.sh tags/v64.1 \
	&& rm -rf /var/lib/apt/lists/*

# Add user
ENV USER pmdkuser
ENV USERPASS pmdkpass
RUN useradd -m $USER -g sudo -p `mkpasswd $USERPASS`

# switch user
USER $USER

# Set required environment variables
ENV OS ubuntu
ENV OS_VER 18.04
ENV START_SSH_COMMAND service ssh start
ENV PACKAGE_MANAGER dpkg
ENV NOTTY 1
